language: node_js
node_js:
   - "6.*"

branches:
  only:
    - master
    - /^greenkeeper-.*$/
    - /^greenkeeper/.*$/

before_script:
    - "npm install --global yarn"
    - "yarn dist"

script:
    - "yarn test:ci"

after_success:
    - SAUCELABS=true yarn test:browser

cache:
  directories:
    - node_modules

notifications:
    email: false

sudo: false
